import AppHeader from "@/components/layout/AppHeader";
import SideBar from "@/components/layout/SideBar";
import { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const layout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <div className="flex">
      <SideBar />
      <div className="w-full">
        <AppHeader />
        <main>{children}</main>
      </div>
    </div>
  );
};

export default layout;
